import React from 'react';
import { ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import '@etransfer/ui-react/dist/assets/index.css';
import '../app/globals.css';

export const metadata: Metadata = {
  title: 'ETransfer toolkit example',
  description: 'Generated by create next app',
};

export default function WebLoginAndAntdLayout({ children }: { children: React.ReactNode }) {
  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: '#285eff',
          colorPrimaryActive: '#1e52f0',
          colorPrimaryHover: '#3b6cff',
          colorError: '#f53f3f',
          colorText: '#1a1a1a',
          colorTextSecondary: '#808080',
          colorTextDisabled: '#d6d6d6',
          colorBorder: '#e0e0e0',
          colorSplit: '#f0f0f0',
        },
      }}>
      {children}
    </ConfigProvider>
  );
}
