import React from 'react';
import type { Metadata } from 'next';
import Provider from '@/provider';
import 'aelf-web-login/dist/assets/index.css';
import '@etransfer/ui-react/dist/assets/index.css';
import './globals.css';
import dynamic from 'next/dynamic';
const ETransferLayout = dynamic(() => import('@/pageComponents/ETransferLayout'), { ssr: false });

export const metadata: Metadata = {
  title: 'ETransfer toolkit example',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ETransferLayout>{children}</ETransferLayout>
        </Provider>
      </body>
    </html>
  );
}
