name: Unit Test

on:
  pull_request:
  push:
    branches:
      - 'release/*'
      - master
      - feature/ut

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn build
      - run: yarn test
      - run: yarn make-badges
